---
- hosts: host1, host2
  become: true
  tasks:
  - name: install apache packages for ubuntu
    apt:
        name: 
            - apache2
            - libapache2-mod-php
        state: latest
        update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install packages for centos
    dnf:
        name: 
            - httpd
            - php
        state: latest
        update_cache: yes
    when: ansible_distribution == "CentOS"
